### ISSUE TITLE
"missing" max_connections in ranch_tcp:opts()?

### ISSUE THREAD

**Issue by sata** [ninenines/ranch#114] opened 2015-07-15 09:25 UTC
I'm having Dialyzer 'non local return' warning in my app when I'm calling cowboy:start_http/4 with max_connections key val in transport options. 

start_http/4 calls ranch:start_listener/6 where TransOpts is being passed through to newly spawned child ranch_listener_sup under ranch_sup[1]. ranch_listener_sup passed it along to ranch_acceptors_sup[2] which in turn calls Transport:listen[3] withTransOpts. in cowboy:start_http/4 case it's ranch_tcp, thus it expects options to be matching types in ranch_tcp:opts() which is missing max_connections.

From what I can see, ranch_tcp doesn't care about max_connections and that property is only needed to update ranch_server[4] from ranch_listener_sup.

I see two options here;  either adding the max_connections to the ranch_tcp:opts() which would be 'wrong' since it's not used in ranch_tcp or filter max_connections out in ranch_listener_sup before it passes it to ranch_acceptors_sup.

What do you think?

[1] https://github.com/ninenines/ranch/blob/02ff6533bbbc5dae95959c4979765d532d9e0af6/src/ranch.erl#L85-L86
[2] https://github.com/ninenines/ranch/blob/02ff6533bbbc5dae95959c4979765d532d9e0af6/src/ranch_listener_sup.erl#L38
[3] https://github.com/ninenines/ranch/blob/02ff6533bbbc5dae95959c4979765d532d9e0af6/src/ranch_acceptors_sup.erl#L30
[4] https://github.com/ninenines/ranch/blob/02ff6533bbbc5dae95959c4979765d532d9e0af6/src/ranch_listener_sup.erl#L24-L25

**Comment by essen** [comment] 2015-07-15 09:29
Definitely not the former.

**Comment by sata** [comment] 2015-07-15 09:43
Mmm, agreed. The other solution doesn't make sense either. Since it already filters in listen and it makes sense to have it there. Question is how to express it with specs without it becoming incomprehensible.

Perhaps adding a type opt() to describe each key value ranch_tcp cares for, then write -spec listen([opt() | tuple()]). This would make it more expressive to show that it can deal with more options than the ones in defined in opt(). 
-type opts() would then be [opt()].

**Comment by essen** [comment] 2015-07-15 09:53
The problem comes from the fact Ranch does not remove max_connections and others before forwarding to the transport function, I believe.

**Comment by sata** [comment] 2015-07-15 10:04
Yes. But there is already filtering function to deal with unwanted options in listen. The code works and it's quite expressive about what it does. Isn't the issue more of conforming the specs to reflect what's actually going on? 

Filtering before transport function can be a bit tricky. Since it would then require a knowledge of what the Transport module is in ranch_acceptors_sup. ranch_tcp has different opts() than ranch_ssl etc.

**Comment by essen** [comment] 2015-07-15 10:11
I mean remove specific options like max_connections, using for example keytake instead of keyfind, so it doesn't leak into ranch_tcp. Perhaps there is also some specs to be fixed, before that point, but if you leave max_connections in the ranch_tcp call then you will still have warnings (or should, anyway).

**Comment by sata** [comment] 2015-07-15 10:35
Ah. I understand.

I will check for more options similiar to max_connections. And write a minor PR to filter out those options in ranch_listener_sup:start_link/6 before it makes the supervisor:start_link call. 

Any ideas on updating the Transport listen specs to reflect that it can handle unwanted options?

**Comment by essen** [comment] 2015-07-15 10:55
We don't want to allow too much in transport because otherwise, what's the point of specs? :-)

**Comment by sata** [comment] 2015-07-19 17:11
From Cowboys perspective the only change that needs to happen is this changing specs to `ranch:opts() | ranch_{tcp,ssl}:opts()`

What do you think?

This should also address PR #102

**Comment by essen** [comment] 2015-07-19 18:03
Yep that would be good.

**Comment by sata** [comment] 2015-07-20 18:30
Should I create a PR on Cowboy now or wait until this gets merged?

**Comment by essen** [comment] 2015-07-20 19:05
Depends if you think you'll have the time later. :-) I won't look for a few more days, resting a bit and waiting for the dust to settle.

**Comment by essen** [comment] 2015-08-17 09:23
Out of curiosity, wondering what Dialyzer option you need enabled to see this error?

**Comment by sata** [comment] 2015-08-17 09:29
I saw it when I ran Dialyzer over a very small application which called cowboy_start_http with max_connections key in transport options.

That should be enough to reproduce it.

**Comment by essen** [comment] 2015-08-17 09:57
Ah got it, thanks.

**Comment by sata** [comment] 2015-08-17 09:59
:+1: 

I haven't forgot about the spec patch for Cowboy. :)

**Comment by essen** [comment] 2015-08-17 10:00
Yep, I am doing this today (+ other things) and releasing 1.2.0 today or tomorrow, and then we can update Cowboy.

**Comment by essen** [comment] 2015-08-17 16:07
Actually my bad, couldn't reproduce, my check was flawed (put max_connections in wrong list :-). But anyway about to push the fix I got, will rely on you to tell me if that's still good. :-)

**Comment by essen** [comment] 2015-08-17 16:26
Changing the types a little because otherwise you can't do "Ranch specific options" | "Transport options". So it will be [ranch:opt() | ranch_tcp:opt()] in Cowboy, for example.

**Comment by sata** [comment] 2015-08-17 16:42
What needed to change to make it work? Because that was my goal :)

**Comment by essen** [comment] 2015-08-17 16:46
If you make something like ranch:opts() = [{max_connections, max_conns()}, ...] and you have something like ranch_tcp:opts(), you can't then do ranch:opts() | ranch_tcp:opts() to show it's a list of both of them, because this means either a list of Ranch-specific options OR a list of ranch_tcp-specific options.

**Comment by essen** [comment] 2015-08-17 16:52
Pushed in d440a2c1d26e4f0770a66279de151806b1ad5ac2. Can you confirm that this works?

**Comment by essen** [comment] 2015-08-18 14:28
Closing to help me see better in what I have left in Ranch 1.2. But do confirm that this works when you got the time. :-)

**Closed by essen** 2015-08-18 14:28 UTC
Labels: Bug
