### ISSUE TITLE
ranch_server:count_connections/1 results in a negative number

### ISSUE THREAD

**Issue by jdicioccio** [ninenines/ranch#95] opened 2014-11-18 19:14 UTC
I'm using Cowboy 1.0.1/Ranch 1.0.0 inside ejabberd on R16B02 to handle websocket connections.  One issue I've noticed is this:

```
(ejabberd@localhost)4> ranch_server:count_connections(ejabberd_sockjs_https).
-3250
(ejabberd@localhost)5> sys:get_status(erlang:list_to_pid("<0.608.0>")).      
{status,<0.608.0>,
        {module,ranch_conns_sup},
        [[{<0.21963.15>,true},
          {<0.15373.18>,true},
          {<0.30534.17>,true},
          {<0.24334.18>,true},
          {<0.4224.13>,true},
          {<0.9254.17>,true},
          {<0.5404.16>,true},
          {<0.26013.18>,true},
          {<0.30583.11>,true},
          {<0.24617.16>,true},
          {<0.1497.0>,true},
          {<0.18870.10>,true},
          {<0.23083.9>,true},
          {<0.26760.6>,true},
          {<0.3010.0>,true},
          {<0.27421.10>,true},
          {<0.26321.13>,true},
          {<0.17893.18>,true},
          {<0.20894.2>,true},
          {<0.7611.11>,true},
          {<0.23505.4>,true},
          {<0.16921.8>,true},
          {<0.32702.10>,...},
          {...}|...],
         running,<0.605.0>,[],
         {{state,<0.605.0>,ejabberd_sockjs_https,worker,5000,
                 ranch_ssl,cowboy_protocol,
                 [{env,[{dispatch,[{'_',[],[{...}]}]}]}],
                 5000,1024},
          -3255,680,[]}]}
```

I assume the mechanism that's used to keep track of active connections is failing somewhere.

**Comment by essen** [comment] 2016-11-15 15:18
I am cherry-picking https://github.com/fishcakez/ranch/commit/c3a3862cabc81b0d223df10a6b82d1d1e334d8e0 and adding a test. Test was very quick to write, and demonstrates that the issue is fixed. I also like `active` more than `current` or `included`.

Closing, thanks!

**Closed by essen** 2016-11-15 15:18 UTC
Labels: Bug
